### ISSUE TITLE
Constant stutters

### ISSUE THREAD

**Issue by hrytskivr** [Questie/Questie#2605]
## Bug description
This addon causes frequent and constantly occuring stutters (~0.5ms) in game, this is very annoying.

## Screenshots
It can't be screenshotted.

## Questie version
6.2.5

- - - 
Windows 10
Ryzen 5 3600
Radeon RX 580

**Comment by hrytskivr** [comment]
This does not depend on any action, at least I haven't noticed it.

**Comment by Gogo1951** [comment]
Hey @hrytskivr ,

Can you include your profiler report? Makes it really impossible to help your issue without more info.

Go to the Options > Advanced Tab, and turn on Profiler while you are experiencing the stutter. Run it for 30 seconds on either side of the stutter ideally, and post a screenshot. That'll help us diagnose.

Cheers!

**Comment by BreakBB** [comment]
@hrytskivr Have you been on a timed quest when you experieced the stutter?

**Comment by asleire** [comment]
Me and a friend notices this while doing two different timed quests. While the timed quest was active, we'd experience occasional stutter. It seemed to ocurr as combat ended. After delivering the timed quests, the stutter disappeared completely even while killing the same mobs that previously made it stutter

**Comment by BreakBB** [comment]
Ah, "great" it is linked to timed quests. I've already opened a PR ( #2601 ) for this a few days back to adress this issue. We will have this fixed in the next version of Questie.

I am closing this issue in favor of the previous issue #2592. Thanks for reporting the issue @asleire

**Comment by hrytskivr** [comment]
> @hrytskivr Have you been on a timed quest when you experieced the stutter?

No, I experienced this leveling trough 1 to 55, I thought this is wow bug itself or something to do with my hardware, then I found on youtube that questie was the issue for someone, I disabled it and now all good.

**Comment by BreakBB** [comment]
Oh damn @hrytskivr sorry for closing this too early.

Could you run the Profiler as Gogo explained above and share a screenshot of the outcome?

You should also try to disable all addons except Questie and see if that makes the game stutter. It might be a conflict with another addon because other users don't have this problem.

And out of curiosity: Could you link the YouTube video you mentioned? :Grin:

**Comment by hrytskivr** [comment]
If you can make profiler run in background instead of taking 90% of the view then I can run it, yes :)

**Comment by hrytskivr** [comment]
Also some stutters still happening without questie, but nowhere near as often,

**Comment by BreakBB** [comment]
Well the video is from 2018 so it uses the private server version of Questie. For Classic we basically did a complete rewrite because of all the API changes so I am not sure if that video has any useful information. But ofc Questie had some issues in the past which lowered framerate by a lot, but I think we tackled all of these issues 🤔 

For the profiler: Yeah it is in a rough shape and not really nice you can't resize it atm, sorry about that. But you are able to move the window partly off screen to see more of you usual UI. We can't really say much without the profiler since for "everyone else" Questie is working just fine :)

**Comment by Gogo1951** [comment]
Closing this, a bug from 2018 private servers is no longer relevant.
