### ISSUE TITLE
Lua Errors on Jewelcrafting Daily Quest

### ISSUE THREAD

**Issue by bugeaggeorge** [Questie/Questie#5074]
## Bug description
Whenever I pick up the Jewelcrafting Daily quest I get a lua error in chat:
```
[23:33:26] Questie: Please note: One of the next Questie releases will reset your settings. We advise you to backup your Questie related Saved Variables as precaution.
[23:33:31] [Y] [Anymoree]: LF Uldu25 Full Run Normal 4SR>MS>OS 'Boe+orb HR - Frag Gbid' Need Few Dps /w me gs&spec
[23:33:32] [Y] <Busy>[Nameleess]: LFM Toc 25m NM / Need All +4.5 GS / x2 SR>MS>OS / Boe HR + Trophy Gbid ( No Split ) Be Patient When Forming Pls
[23:33:35] Quest accepted: Jewel Of The Sewers
[23:33:43] [Y] [Bochelini]: LFM Togc 25 Man 4/5 HC GDKP 80/20  Need  Dps Mix/Buyer + 1Hapal - MinBid:5K - Bis:10K  Going When Full 22/25
[23:33:43] Sold junk for 25 Gold.
[23:33:45] [Y] [75:Blackston]: need 2 tank and heal for togc 10 man 2xsr 50/50 link achiv for [inv]
[23:34:01] [Y] <Busy>[Nameleess]: LFM Toc 25m NM / Need All +4.5 GS / x2 SR>MS>OS / Boe HR + Trophy Gbid ( No Split ) Be Patient When Forming Pls
[23:34:04] [Y] [Anymoree]: LF Uldu25 Full Run Normal 4SR>MS>OS 'Boe+orb HR - Frag Gbid' Need Few Dps Sp, Shammy, Hunter, Lock /w me gs&spec
[23:34:18] [Y] [Bochelini]: LFM Togc 25 Man 4/5 HC GDKP 80/20  Need  Dps Mix/Buyer + 1Hapal - MinBid:5K - Bis:10K  Going When Full 22/25
[23:34:44] [Y] [Anymoree]: LF Uldu25 Full Run Normal 4SR>MS>OS 'Boe+orb HR - Frag Gbid' Need Few Dps Sp, Shammy, Hunter, Lock /w me gs&spec
[23:34:46] [Y] [Bochelini]: LFM Togc 25 Man 4/5 HC GDKP 80/20  Need  Dps Mix/Buyer + 1Hapal - MinBid:5K - Bis:10K  Going When Full 22/25
[23:34:49] [Y] [75:Blackston]: need 2 tank and heal for togc 10 man 2xsr 50/50 link achiv for [inv]
[23:35:00] Quest accepted: Shipment: Shifting Sun Curio
[23:35:00] Interface/AddOns/Questie/Modules/Map/QuestieMap.lua:574: No UiMapID or fitting parentAreaId for areaId : 4277 - Forgotten Footman
[23:35:00] [string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:70: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:68>
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/Questie/Modules/Map/QuestieMap.lua"]:574: in function `DrawWorldIcon'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1381: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1374>
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1131: in function <...erface/AddOns/Questie/Modules/Quest/QuestieQuest.lua:1070>
[string "=[C]"]: in function `xpcall'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:838: in function `UpdateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:1424: in function `PopulateObjectiveNotes'
[string "@Interface/AddOns/Questie/Modules/Quest/QuestieQuest.lua"]:471: in function `val'
[string "@Interface/AddOns/Questie/Modules/TaskQueue.lua"]:8: in function <Interface/AddOns/Questie/Modules/TaskQueue.lua:6>

[23:35:00] Questie: [ERROR] [QuestieQuest]: [SpecialObjectives] There was an error populating objectives for Shipment: Shifting Sun Curio 12963 0 No error
```

## Screenshots
![image](https://github.com/Questie/Questie/assets/22823892/3fcecbe4-2e5c-4d4e-92d5-d16317de9b6f)

## Questie & WoW version
- Questie version: 8.8.5
- WoW Version: WoW Classic WOTLK

**Comment by Cabro** [comment]
This is already fixed in https://github.com/Questie/Questie/pull/5073 . Waiting for update

**Comment by spfaffly** [comment]
The new update fixed it - but I had to "Reset Questie" in order for the error to completely go away.

**Comment by Cabro** [comment]
What do you mean? Can you give me more details?

**Comment by spfaffly** [comment]
I can't recreate now after clicking the "Reset Questie" button - but it was still throwing errors on Jewelcrafting dailies - sorry I didn't capture the exact errors.

**Comment by spfaffly** [comment]
That might have happened - questie was still updating while I hit accept.

**Comment by Aenimma** [comment]
Hello, I am still getting errors when getting the JC daily plus many other daily quests.

Date: 2023-08-24 17:42:49
ID: 1
Error occured in: Global
Count: 1
Message: ...terface/AddOns/DataStore_Quests/DataStore_Quests.lua line 232:
   attempt to call global 'GetNumQuestLogRewardSpells' (a nil value)
Debug:
   [string "@Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua"]:146:
      ...tCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:144
   [string "=[C]"]: GetNumQuestLogRewardSpells()
   [string "@Interface/AddOns/DataStore_Quests/DataStore_Quests.lua"]:232:
      ...terface/AddOns/DataStore_Quests/DataStore_Quests.lua:229
   [string "@Interface/AddOns/DataStore_Quests/DataStore_Quests.lua"]:310:
      ...terface/AddOns/DataStore_Quests/DataStore_Quests.lua:246
   [string "@Interface/AddOns/DataStore_Quests/DataStore_Quests.lua"]:335:
      ...terface/AddOns/DataStore_Quests/DataStore_Quests.lua:333
   [string "=[C]"]: ?
   [string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19:
      ...ore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15
   [string "@Interface/AddOns/DataStore/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: Fire()
   [string "@Interface/AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120:
      .../AddOns/DataStore/libs/AceEvent-3.0/AceEvent-3.0.lua:119
Locals:
private = <table> {
 ThrowError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:77
 NewError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface/AddOns/RCLootCouncil_Classic/RCLootCouncil/Core/ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface/AddOns/Decursive/Dcr_DIAG.lua:611

**Comment by MyTechnoHunter** [comment]
You do realize that data store quests is part of alcoholic not questie, yes?

**Comment by bugeaggeorge** [comment]
Seems to be fixed with the new update.

@Aenimma you should read the error, you'll find out that it's actually coming from another addon.

**Comment by BreakBB** [comment]
As a bonus for @Aenimma because I just stumbled over it: Checkout [this reddit post](https://www.reddit.com/r/classicwow/comments/15ivrib/datastore_quests_issue/) for a fix

**Comment by MyTechnoHunter** [comment]
@BreakBB the altoholic discord has the fixed quest file pinned in its relevant bug channel
